### ISSUE TITLE
aarch64 architecture

### ISSUE THREAD

**Issue by AdrienForestier** [VowpalWabbit/py-vowpalwabbit-next#106]
Hey,
I'm trying to install vowpal-wabbit-next on an aarch64 linux, but there's no wheel for that architecture. And when it comes to trying to instsall through source and build it locally, I got this error :

```
Collecting vowpal-wabbit-next
  Downloading vowpal-wabbit-next-0.7.0.tar.gz (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 11.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-qmva8wh7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-qmva8wh7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-qmva8wh7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 19, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-q8t3gw1j/vowpal-wabbit-next_8edbdd80929c41bdac39843911aa079e/version.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

If anybody got a solution for that, I'm down for it.
Thanks

**Comment by theobouwman** [comment]
Did you manage to solve this?

**Comment by AdrienForestier** [comment]
Nop, I went back to vowpalwabbit
